---

# This GitHub Actions workflow is designed to be triggered when a release is marked as a full release.
# The workflow performs the following tasks:.
# 1. Builds and publishes a Docker image.
# 2. Creates a GitHub release.

name: Release And Publish Docker Artifact

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'
permissions:
  contents: write
  packages: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        if: ${{ !inputs.dry-run }}
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v2.0.10
        with:
          ref: main
          tag-name: v${{ github.event.inputs.version }}
          tag-message: Tag v${{ github.event.inputs.version }}
          dry-run: ${{ inputs.dry-run }}

  core-base-docker-build:
    needs: [ create-tag ]
    name: Build Docker image
    uses: Netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@32a5b506971a029acc41bc69fd42d06137caeb36
    with:
      build-args: |
        BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-core-base:${{ inputs.version }}
      tags: "${{ inputs.version }}"
      config-filename: "core-base-docker-release-config.json"
      dry-run: ${{ inputs.dry-run }}

  java-prof-21-docker-build:
    needs: [create-tag, core-base-docker-build]
    name: Build Docker image
    uses: Netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@32a5b506971a029acc41bc69fd42d06137caeb36
    with:
      build-args: |
        BASE_IMAGE=ghcr.io/netcracker/qubership-core-base:${{ inputs.version }}
        BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base-prof:21-alpine-${{ inputs.version }}
      tags: "21-alpine-${{ inputs.version }},21-alpine-latest"
      config-filename: "java-prof-21-docker-release-config.json"
      dry-run: ${{ inputs.dry-run }}

  java-25-docker-build:
    needs: [create-tag, core-base-docker-build]
    name: Build Docker image
    uses: Netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@32a5b506971a029acc41bc69fd42d06137caeb36
    with:
      build-args: |
        BASE_IMAGE=ghcr.io/netcracker/qubership-core-base:${{ inputs.version }}
        BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base:25-alpine-${{ inputs.version }}
      tags: "25-alpine-${{ inputs.version }},25-alpine-latest"
      config-filename: "java-25-docker-release-config.json"
      dry-run: ${{ inputs.dry-run }}

  java-prof-25-docker-build:
    needs: [create-tag, java-25-docker-build]
    name: Build Docker image
    uses: Netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@32a5b506971a029acc41bc69fd42d06137caeb36
    with:
      build-args: |
        BASE_IMAGE=ghcr.io/netcracker/qubership-java-base:25-alpine-${{ inputs.version }}
        BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base-prof:25-alpine-${{ inputs.version }}
      tags: "25-alpine-${{ inputs.version }},25-alpine-latest"
      config-filename: "java-prof-25-docker-release-config.json"
      dry-run: ${{ inputs.dry-run }}

  github-release:
    needs: [create-tag]
    if: ${{ !inputs.dry-run }}
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v2.0.10
    with:
      version: ${{ github.event.inputs.version }}
      publish: false