---

# This GitHub Actions workflow is designed to be triggered when a release is marked as a full release.
# The workflow performs the following tasks:.
# 1. Builds and publishes a Docker image.
# 2. Creates a GitHub release.

name: Release And Publish Docker Artifact

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'
permissions:
  contents: write
  packages: write

jobs:
  java-base-docker-build:
    name: Build Docker image
    uses: Netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v1.1.1
    with:
      tags: "21-alpine-${{ inputs.version }}"
      config-filename: "java-base-docker-release-config.json"
      dry-run: ${{ inputs.dry-run }}

  core-base-docker-build:
    name: Build Docker image
    uses: Netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v1.1.1
    with:
      config-filename: "core-base-docker-release-config.json"
      dry-run: ${{ inputs.dry-run }}
