---
# yamllint disable rule:line-length
name: Build and Push On Commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      [opened, reopened, synchronize]

env:
  PLATFORMS: linux/amd64,linux/arm64

permissions:
  contents: read
  packages: write

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    steps:
      - id: tag_build_number
        run: echo "tag=$(echo '${{github.ref_name}}' | tr -cs 'a-zA-Z0-9' '-')$(date +'%Y%m%d%H%M%S')-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - id: tag_snapshot
        run: echo "tag=$(echo '${{github.ref_name}}' | tr -cs 'a-zA-Z0-9' '-')snapshot" >> "$GITHUB_OUTPUT"
    outputs:
      tag_build_number: ${{ steps.tag_build_number.outputs.tag }}
      tag_snapshot: ${{ steps.tag_snapshot.outputs.tag }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare-variables
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      
      - name: Build and load test core-image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-core-base:test
          tags: |
            ghcr.io/netcracker/qubership-core-base:test
          file: images/core/Dockerfile

      - name: Build and load test java 21 image with prof
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/netcracker/qubership-core-base:test
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base-prof:test
          tags: |
            ghcr.io/netcracker/qubership-java-base:21-test
            ghcr.io/netcracker/qubership-java-base-prof:21-test
          file: images/java-21-prof/Dockerfile

      - name: Build and load test java 25 image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/netcracker/qubership-core-base:test
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base:test
          tags: ghcr.io/netcracker/qubership-java-base:25-test
          file: images/java-25/Dockerfile

      - name: Build and load test java 25 image with prof
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/netcracker/qubership-java-base:25-test
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base-prof:25-test
          tags: ghcr.io/netcracker/qubership-java-base-prof:25-test
          file: images/java-25-prof/Dockerfile

      - name: Test ca certificates were processed correctly
        run: |
          ./tests/certificates/test-certificates-processing.sh ghcr.io/netcracker/qubership-core-base:test
          ./tests/certificates/test-certificates-processing.sh ghcr.io/netcracker/qubership-java-base-prof:21-test
          ./tests/certificates/test-certificates-processing.sh ghcr.io/netcracker/qubership-java-base:25-test
          ./tests/certificates/test-certificates-processing.sh ghcr.io/netcracker/qubership-java-base-prof:25-test

      - name: Test OS signal propagation
        run: |
          ./tests/signal-propagation/test-signal-propagation.sh ghcr.io/netcracker/qubership-core-base:test

      - name: Validate version "test" in log output
        run: |
           docker run --rm ghcr.io/netcracker/qubership-core-base:test | grep "Base image version: ghcr.io/netcracker/qubership-core-base:test"

      - name: Set up JDK 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          distribution: zulu
          java-version: 21
          server-id: central

      - name: Cache local Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test profiler integration
        working-directory: test-profiler
        # language=bash
        run: |
          ./mvnw --batch-mode verify -Dqubership.profiler.java-base-image.tag=ghcr.io/netcracker/qubership-java-base:21-test
          ./mvnw --batch-mode verify -Dqubership.profiler.java-base-image.tag=ghcr.io/netcracker/qubership-java-base-prof:25-test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push core-base image
        uses: docker/build-push-action@v6
        with:
          push: ${{ !startsWith(github.ref, 'refs/heads/dependabot/') }}
          build-args: |
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-core-base:${{ needs.prepare-variables.outputs.tag_build_number }}
          tags: |
            ghcr.io/netcracker/qubership-core-base:${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership-core-base:${{ needs.prepare-variables.outputs.tag_build_number }}
          file: images/core/Dockerfile
          platforms: ${{ env.PLATFORMS }}


      - name: Build and push java-image-21
        uses: docker/build-push-action@v6
        with:
          push: ${{ !startsWith(github.ref, 'refs/heads/dependabot/') }}
          build-args: |
            BASE_IMAGE=ghcr.io/netcracker/qubership-core-base:${{ needs.prepare-variables.outputs.tag_build_number }}
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base-prof:21-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
          tags: |
            ghcr.io/netcracker/qubership-java-base:21-alpine-${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership-java-base:21-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
            ghcr.io/netcracker/qubership-java-base-prof:21-alpine-${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership-java-base-prof:21-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
          file: images/java-21-prof/Dockerfile
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push java-image-25
        uses: docker/build-push-action@v6
        with:
          push: ${{ !startsWith(github.ref, 'refs/heads/dependabot/') }}
          build-args: |
            BASE_IMAGE=ghcr.io/netcracker/qubership-cseore-ba:${{ needs.prepare-variables.outputs.tag_build_number }}
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base:25-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
          tags: |
            ghcr.io/netcracker/qubership-java-base:25-alpine-${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership-java-base:25-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
          file: images/java-25/Dockerfile
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push java-image-25-prof
        uses: docker/build-push-action@v6
        with:
          push: ${{ !startsWith(github.ref, 'refs/heads/dependabot/') }}
          build-args: |
            BASE_IMAGE=ghcr.io/netcracker/qubership-java-base:25-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
            BASE_IMAGE_TAG=ghcr.io/netcracker/qubership-java-base-prof:25-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
          tags: |
            ghcr.io/netcracker/qubership-java-base-prof:25-alpine-${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership-java-base-prof:25-alpine-${{ needs.prepare-variables.outputs.tag_build_number }}
          file: images/java-25-prof/Dockerfile
          platforms: ${{ env.PLATFORMS }}